### ISSUE TITLE
Failure in installing the package

### ISSUE THREAD

**Issue by gdh14** [liqun730/QRADMM-package#1]
Hi,

I'm quite interested in ADMM for penalized quantile regession, yet error occurs during the installation:
#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
Could you help me figure out this problem? Thank you.

**Comment by liqun730** [comment]
Hi, thanks for pointing this out! I ran into the same issue when installing the package on Windows. The installation however works just fine for MAC OS. I will try to find the reason and solve the issue. Thanks!

**Comment by Scott-Coggeshall** [comment]
I was able to get the package to install on Windows by adding a Makevars.win file to 'src' folder. Open a text editor, paste the following into it and then save as src/Makevars.win:

>\#\# With R 3.1.0 or later, you can uncomment the following line to tell R to 
>\#\# enable compilation with C++11 (where available)
>\#\#
>\#\# Also, OpenMP support in Armadillo prefers C++11 support. However, for wider
>\#\# availability of the package we do not yet enforce this here.  It is however
>\#\# recommended for client packages to set it.
>\#\#
>\#\# And with R 3.4.0, and RcppArmadillo 0.7.960.*, we turn C++11 on as OpenMP
>\#\# support within Armadillo prefers / requires it
>CXX_STD = CXX11
>
>PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS) 
>PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
